### ISSUE TITLE
Pour info

### ISSUE THREAD

**Issue by jeromefiot** [GeekPress/WP-Quick-Install#13]
J'ai créé un script shell pour automatiser encore plus et créer:

 - la base (du nom de l'argument = projet) et le user (nom = projet / passwd = projet123!) correspondant MySQL
 - le virtualhost apache2 et activer le site
 - Le repo Git pour faire une sauvegarde de tout ca

Avec en plus le .htaccess qui me semble optimisé pour cela et le .gitignore
N'hésitez pas à me dire ce que vous en pensez (@grominet)

**Comment by GeekPress** [comment]
Salut Jérôme,

Merci pour ce script shell :)

**Comment by jeromefiot** [comment]
Tu plaisantes, merci à toi pour la "grosse partie" !
Par contre lors de mon dernier essai j'avais toujours ce "problème" (freeze) au moment de la mise en place de la base (propre à version 4.0 ?)

**Comment by GeekPress** [comment]
Oui, le problème est survenue depuis WordPress 4.1, mais je viens juste de sortir la version 1.4 qui règle le problème :)

**Comment by jeromefiot** [comment]
Respect & big thx
