### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by olivervo** [GeekPress/WP-Quick-Install#8]
It seems like the plugin by default creates a new directory called "wordpress" in the wp-quick-install directory even though I've specified another path in the installation route field. Is this a bug? It would be great if you could install wordpress to another directory using the tool.

**Comment by GeekPress** [comment]
Hi there,

I'm pretty sorry for the delay.

It's not a bug, it was the cache folder for WordPress files, to not have to download WP each time.
